services:
  sqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SpikeOnly!Passw0rd"

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    depends_on:
      - sqledge
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "SpikeOnly!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "5672:5672"
      - "5300:5300"
    volumes:
      - ./Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
